[project]
name = "intellinote-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "dotenv>=0.9.9",
    "openai-agents>=0.6.1",
    "pypdf>=6.3.0",
    "pypdf2>=3.0.1",
    "streamlit>=1.51.0",
]
